### PR TITLE
Multiple primary keys

### PR DESCRIPTION
**Pull request by mfa**
Added support for multiple primary keys using | as separator.
Includes some tests for sqlalchemy.

### CODE REVIEW

**Comment by wilsaj** [comment]
Hi Andreas. Thanks for working on this.

How do you feel about using '/' instead of '|' as the separator? All we'd need to do to make that work is to use `'.../<path:model_key>/'` in the url rules and then they can pull in model_keys which could be something like "some_name/2038941/342". I think it would make the urls a little more natural (without having to escaped '|' chars in them).

I can work on the particulars, but do you have strong opinions on this?

**Comment by mfa** [comment]
Ok for me. If a problem occurs we can add a parameter for the separator.
The only problem can be when the pk is not the last argument in the url, which is not the case atm.

I tried the change (two replaces of | with /) and the tests are working just fine.

**Comment by wilsaj** [comment]
I've pulled your branch into my own multi-primary-keys branch and made a few tweaks. Can you check those out and let me know what you think?

side note: I don't know if there's a good way to link my branch to this PR... maybe you can pull those changes into your branch if you're cool with them?

**Comment by mfa** [comment]
Hi Andy,

after pulling you branch and testing your changes in my web-app everything seems fine to me.
From my point of view there should be no problem merging your multi-pk-branch into master.

**Comment by mfa** [comment]
after updating the tests there seems to be a problem with empty keys.
when in the url is a // at the end, the routing gives a 404; but this should be possible.

**Comment by wilsaj** [comment]
Good catch! This isn't going to work if there are null values in some parts of the composite keys.

I'm pretty sure it can technically be made to work within the context of Flask/Werkzeug but I think that having multiple slashes in URLs is going to cause headaches elsewhere since there seems to be confusion about what the situation is regarding multiple-slashes in URLs and some people/clients normalize multiple slashes to single slashes. And "http://server.com/admin/edit/SomeModel//1//' is not the same thing as "http://server.com/admin/edit/1/SomeModel///' but both would reduce to '"http://server.com/admin/SomeModel/edit/1/'

So the options I can think of are:
1. Require composite keys be non-null. This is too much of a restriction so we can throw this out.
2. Replace nulls with some other string for the purpose of encoding/decoding URLs. For example, nulls will always be encoded as '%00' (ascii null character).
3. Replace the separator with some character for the purpose of encoding/decoding URLs. For example, '|' as you proposed.  
4. Generalize the approach by allowing people to specify a function for encoding keys and a function for decoding keys (or an object that encapsulates these functions as methods).

For options 2 and 3, I don't like that it reduces what people can use for their keys. For example if we use '|' as the separator, then someone comes along and stores a string that has that character in it, things will break. We can allow the option of specifying the separator or null-encoded value to use, so that will help a bit. Of these two options I'm leaning towards encoded null values because it reduces the space of things you can use as keys only by one character sequence rather than eliminating any string or character sequence containing the separator value.

I like the 4th option because it gives developers the most control but I have a feeling it might not ever be used and would just make the API more complicated than it needs to be.

**Comment by mfa** [comment]
First, Google Chrome seems to have a problem with %00 :(
So I implemented a version with %01 as empty_char that can be set in the datastore.

**Comment by wilsaj** [comment]
There's a class of web vulnerabilities based on the idea that you can trick people into visiting a website that looks legit by sticking a null character in the URL. So you might think you're visiting "http://www.example.com/allmybankmoneys/" when it is actually "http://www.exam%00ple.com/allmybankmoneys/". So maybe ignoring urls with null characters is the right thing to do.

It looks like the [substitute character](http://en.wikipedia.org/wiki/Substitute_character), %1a, is a control code that is more or less designated for this purpose. I'll make the change and merge it tonight.

Thanks for making this happen.

**Pull request merged**
